"use client";

import Link from "next/link";
import { FormEvent, useMemo, useState } from "react";
import { calculateBmi, weightComorbidities } from "@/lib/clinical/weight-management-protocol";
import NewServiceCheckout from "@/components/NewServiceCheckout";

const labels: Record<string,string> = { hypertension: "Hipertensión arterial", dyslipidemia: "Dislipidemia", prediabetes: "Prediabetes", type2_diabetes: "Diabetes mellitus tipo 2", sleep_apnea: "Apnea obstructiva del sueño", cardiovascular_disease: "Enfermedad cardiovascular" };
const safety = [["pregnant","Embarazo actual"],["breastfeeding","Lactancia"],["planningPregnancy","Intención de embarazo próxima"],["medullaryThyroidCancerOrMen2","Antecedente personal o familiar relevante de carcinoma medular tiroideo/MEN2"],["semaglutideHypersensitivity","Hipersensibilidad conocida a semaglutida"],["pancreatitis","Antecedente de pancreatitis"],["relevantBiliaryDisease","Enfermedad biliar relevante"],["severeGastroparesisSymptoms","Síntomas de vaciamiento gástrico severamente alterado"],["relevantKidneyDisease","Enfermedad renal relevante"],["usingOtherGlp1OrTirzepatide","Uso actual de otro GLP-1 o tirzepatida"],["usingInsulinOrSulfonylurea","Uso de insulina o sulfonilureas"],["bariatricSurgery","Cirugía bariátrica"]] as const;
export default function WeightPage() {
 const [height,setHeight]=useState(170); const [weight,setWeight]=useState(80); const bmi=useMemo(()=>calculateBmi(weight,height),[weight,height]); const [result,setResult]=useState<{id:string;outcome:string;bmi:number}|null>(null); const [error,setError]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault(); const d=new FormData(e.currentTarget); const payload={age:Number(d.get("age")),sex:d.get("sex"),heightCm:height,weightKg:weight,bodyFatPct:d.get("bodyFatPct")?Number(d.get("bodyFatPct")):null,comorbidities:weightComorbidities.filter(x=>d.get(x)==="on"),safety:Object.fromEntries(safety.map(([k])=>[k,d.get(k)==="yes"]))}; const r=await fetch("/api/new-services/weight-management",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}); const b=await r.json(); if(!r.ok)return setError(b.error); setResult(b); }
 return <main className="veramed-page min-h-screen px-5 py-12"><div className="mx-auto max-w-3xl"><p className="veramed-kicker">Control de peso · evaluación gratuita</p><h1 className="veramed-display mt-3 text-4xl">Descubre si podrías ser candidato</h1><p className="mt-4 text-slate-600">La encuesta no tiene costo. Las reglas se calculan en el servidor y un médico revisa tu caso antes de cualquier tratamiento.</p><section className="veramed-panel mt-8 p-6 md:p-8">{!result?<form className="space-y-7" onSubmit={submit}><div className="grid gap-4 sm:grid-cols-2"><Input name="age" label="Edad" type="number" required/><label className="text-sm font-semibold">Sexo<select name="sex" required className="mt-2 w-full rounded-2xl border border-slate-300 p-3"><option value="female">Femenino</option><option value="male">Masculino</option><option value="other">Otro</option></select></label><Input label="Talla (cm)" type="number" value={height} onChange={e=>setHeight(Number(e.target.value))}/><Input label="Peso (kg)" type="number" value={weight} onChange={e=>setWeight(Number(e.target.value))}/><Input name="bodyFatPct" label="Grasa corporal % (opcional)" type="number"/><div className="rounded-2xl bg-emerald-50 p-4"><span className="text-sm text-emerald-800">IMC calculado</span><strong className="block text-2xl text-emerald-950">{bmi}</strong></div></div><fieldset><legend className="font-semibold">Comorbilidades asociadas al peso</legend><div className="mt-3 grid gap-2 sm:grid-cols-2">{weightComorbidities.map(x=><label key={x} className="rounded-xl border border-slate-200 p-3 text-sm"><input name={x} type="checkbox" className="mr-2"/>{labels[x]}</label>)}</div></fieldset><fieldset><legend className="font-semibold">Seguridad</legend><p className="mt-1 text-sm text-slate-500">Marca Sí sólo cuando el antecedente está presente.</p><div className="mt-3 space-y-3">{safety.map(([k,l])=><div key={k} className="flex items-center justify-between gap-3 border-b border-slate-100 pb-3 text-sm"><span>{l}</span><span className="flex gap-3"><label><input required type="radio" name={k} value="yes"/> Sí</label><label><input required type="radio" name={k} value="no"/> No</label></span></div>)}</div></fieldset><button className="veramed-primary-button w-full px-5 py-3">Ver resultado gratis</button>{error&&<p className="text-red-700">{error}</p>}</form>:<WeightResult id={result.id} outcome={result.outcome} bmi={result.bmi} onError={setError}/>}</section></div></main>;
}
function Input(props:React.InputHTMLAttributes<HTMLInputElement>&{label:string}){const {label,...rest}=props;return <label className="text-sm font-semibold">{label}<input {...rest} className="mt-2 w-full rounded-2xl border border-slate-300 p-3"/></label>}
function WeightResult({id,outcome,bmi,onError}:{id:string;outcome:string;bmi:number;onError:(v:string)=>void}){if(outcome==="standard_path")return <div><h2 className="text-2xl font-semibold text-emerald-800">Por tus respuestas, podrías ser candidato a tratamiento con semaglutida.</h2><p className="mt-3 text-slate-600">IMC: {bmi}. El protocolo automático validará el caso antes de emitir los documentos correspondientes.</p><h3 className="mt-5 font-semibold">Plan inicial de control de peso</h3><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-slate-600"><li>Evaluación estructurada y validación protocolizada</li><li>Prescripción cuando corresponda y plan de hasta 6 meses</li><li>Derivación a nutricionista y guía general de fuerza</li><li>Información de seguridad y señales de alarma</li></ul><NewServiceCheckout orderId={id} baseAmount={7990} onError={onError}/></div>; if(outcome==="medical_review_required")return <div><h2 className="text-2xl font-semibold">Tu caso necesita una evaluación médica antes de decidir si semaglutida es adecuada.</h2><p className="mt-3 text-slate-600">La consulta puede terminar en semaglutida, otra alternativa o en la recomendación de no usar medicamentos.</p><Link className="veramed-primary-button mt-6 px-5 py-3" href="/telemedicina?source=weight-management">Agendar evaluación · $19.990</Link></div>; return <div><h2 className="text-2xl font-semibold">Por tus respuestas, no vemos una indicación clara para iniciar semaglutida mediante el flujo simplificado.</h2><div className="mt-6 flex flex-wrap gap-3"><Link className="veramed-primary-button px-5 py-3" href="/telemedicina?source=weight-alternatives">Hablar con un médico · $19.990</Link><a className="veramed-secondary-button px-5 py-3" href="#recomendaciones">Ver recomendaciones generales</a></div></div>}
