"use client";
import Image from "next/image";
import { useState } from "react";
import { validateDiscountCode } from "@/lib/discount-api";
import { startNewServicePayment } from "@/lib/new-service-payment";

export default function NewServiceCheckout({orderId,baseAmount,requestType="new_service",onError}:{orderId:string;baseAmount:number;requestType?:"new_service"|"telemedicine";onError?:(message:string)=>void}){
  const [code,setCode]=useState("");const [applied,setApplied]=useState("");const [amount,setAmount]=useState(baseAmount);const [message,setMessage]=useState("");const [loading,setLoading]=useState(false);
  async function apply(){try{const result=await validateDiscountCode({requestType,requestId:orderId,code});setApplied(result.appliedCode);setAmount(result.pricing.finalAmount);setMessage(`Código aplicado. Nuevo total: $${result.pricing.finalAmount.toLocaleString("es-CL")}`)}catch(e){setApplied("");setAmount(baseAmount);setMessage(e instanceof Error?e.message:"Código no válido")}}
  async function pay(){setLoading(true);try{await startNewServicePayment(orderId,amount,applied)}catch(e){const value=e instanceof Error?e.message:"No pudimos continuar.";setMessage(value);onError?.(value);setLoading(false)}}
  return <div className="mt-6"><div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-500">¿Tienes un código de descuento?</p><div className="mt-2 flex gap-2"><input value={code} onChange={e=>{setCode(e.target.value.toUpperCase());setApplied("");setAmount(baseAmount)}} className="min-w-0 flex-1 rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm" placeholder="Ingresa tu código"/><button type="button" onClick={apply} className="rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-semibold">Aplicar</button></div>{message?<p className="mt-2 text-xs font-medium text-slate-600">{message}</p>:null}</div><button type="button" onClick={pay} disabled={loading} className="mt-4 mx-auto flex min-h-[82px] w-full max-w-[560px] items-center justify-center rounded-2xl border-2 border-slate-300 bg-slate-50 px-5 py-4 shadow-sm transition hover:bg-white disabled:opacity-60" aria-label={amount===0?"Confirmar orden médica gratis":"Pagar con Webpay Plus"}>{amount===0?<span className="text-center text-base font-bold text-emerald-800">Felicitaciones, tienes tu orden médica gratis 😊</span>:<Image src="/brand/webpay-plus.svg" alt="Webpay Plus Transbank" width={250} height={62} className="h-auto w-[210px]"/>}</button><p className="mt-2 text-center text-xs text-slate-500">{loading?(amount===0?"Confirmando tu orden gratis…":"Redirigiendo a Webpay…"):`Total: $${amount.toLocaleString("es-CL")}`}</p></div>
}
