"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { renewableMedications } from "@/lib/clinical/prescription-renewal-protocol";
import NewServiceCheckout from "@/components/NewServiceCheckout";

export default function RenewPrescriptionPage() {
  const [result, setResult] = useState<{id:string;outcome:string}|null>(null); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = new FormData(event.currentTarget);
    const payload = { medicationId: data.get("medicationId"), dose: data.get("dose"), frequency: data.get("frequency"), since: data.get("since"), indication: data.get("indication"), sameDose: data.get("sameDose") === "yes", importantAdverseEffects: data.get("adverse") === "yes", importantHealthChanges: data.get("changes") === "yes", newMedications: data.get("newMedications") };
    const response = await fetch("/api/new-services/prescription-renewal", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json();
    if (!response.ok) return setError(body.error); setResult(body);
  }
  return <main className="veramed-page min-h-screen px-5 py-12"><div className="mx-auto max-w-2xl"><p className="veramed-kicker">Renovar receta · $4.990</p><h1 className="veramed-display mt-3 text-4xl">Renueva un tratamiento habitual</h1><p className="mt-4 text-slate-600">Sólo para tratamientos elegibles. No incluye medicamentos sujetos a control especial ni tratamientos nuevos.</p>
  <section className="veramed-panel mt-8 p-6 md:p-8">{!result ? <form className="space-y-5" onSubmit={submit}><Field label="¿Qué medicamento necesitas renovar?"><select name="medicationId" required className="w-full rounded-2xl border border-slate-300 p-3"><option value="">Selecciona</option>{renewableMedications.map((m) => <option key={m.id} value={m.id}>{m.displayName}</option>)}</select></Field><Field label="Dosis actual"><input name="dose" required className="w-full rounded-2xl border border-slate-300 p-3" /></Field><Field label="Frecuencia"><input name="frequency" required className="w-full rounded-2xl border border-slate-300 p-3" /></Field><Field label="¿Desde cuándo lo usas?"><input name="since" required className="w-full rounded-2xl border border-slate-300 p-3" /></Field><Field label="Diagnóstico o motivo"><textarea name="indication" required className="w-full rounded-2xl border border-slate-300 p-3" /></Field><YesNo name="sameDose" label="¿Sigues usando la misma dosis?" /><YesNo name="adverse" label="¿Has tenido efectos adversos importantes?" /><YesNo name="changes" label="¿Has tenido cambios importantes de salud?" /><Field label="Medicamentos nuevos relevantes (opcional)"><input name="newMedications" className="w-full rounded-2xl border border-slate-300 p-3" /></Field><button className="veramed-primary-button w-full px-5 py-3">Evaluar renovación</button>{error && <p className="text-sm text-red-700">{error}</p>}</form> : result.outcome === "eligible_for_renewal" ? <div><h2 className="text-xl font-semibold text-emerald-800">Este tratamiento puede solicitarse mediante renovación online.</h2><p className="mt-3 text-slate-600">La receta se emitirá mediante validación automática del protocolo.</p><NewServiceCheckout orderId={result.id} baseAmount={4990} onError={setError}/>{error&&<p className="mt-3 text-sm text-red-700">{error}</p>}</div> : <div><h2 className="text-xl font-semibold">Para renovar este tratamiento necesitamos una evaluación médica.</h2><Link className="veramed-primary-button mt-6 px-5 py-3" href="/telemedicina?source=prescription-renewal">Agendar telemedicina · $19.990</Link></div>}</section></div></main>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-2 block text-sm font-semibold text-slate-800">{label}</span>{children}</label>; }
function YesNo({ name, label }: { name: string; label: string }) { return <fieldset><legend className="text-sm font-semibold text-slate-800">{label}</legend><div className="mt-2 flex gap-4"><label><input required type="radio" name={name} value="yes" /> Sí</label><label><input required type="radio" name={name} value="no" /> No</label></div></fieldset>; }
